apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "product.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "product.fullname" . }}
  podManagementPolicy: Parallel
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "product.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "product.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "product.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          startupProbe:
{{ toYaml .Values.startupProbe | indent 12 }}
          env:
            {{ if .Values.java.javaOpts }}
            - name: JAVA_OPTS
              value: {{ .Values.java.javaOpts }} 
            {{ end }} 
            - name: JAEGER_AGENT_HOST
              {{ if .Values.jaegerAgent.host }}
              value: "{{ .Values.jaegerAgent.host }}"
              {{ else }}
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
              {{ end }}
            - name: JAEGER_AGENT_PORT
              value: "{{ .Values.jaegerAgent.port }}"
            - name: SPRING_CONFIG_LOCATION
              value: /home/application/config/
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ required "secret.name is required"  .Values.secrets.name }}"
                  key: "{{ required "secret.userkey is required"  .Values.secrets.userkey }}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ required "secret.name is required"  .Values.secrets.name }}"
                  key: "{{ required "secret.passwordkey is required" .Values.secrets.passwordkey }}"
            - name: TRUST_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ required "secret.name is required"  .Values.secrets.name }}"
                  key: "{{ required "secret.truststorepassword is required" .Values.secrets.truststorepassword }}"
            - name: KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ required "secret.name is required"  .Values.secrets.name }}"
                  key: "{{ required "secret.keystorepassword is required" .Values.secrets.keystorepassword }}"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- if .Values.productSpecifications.local }}
            - name: productspecifications
              mountPath: /home/application/productSpecifications/
          {{- else if .Values.productSpecifications.prod }}
            - name: productspec
              mountPath: /home/application/productSpecifications/                    
          {{- end }}
          {{- if .Values.git.local }}
            - name: git
              mountPath: /home/application/git/git-workspace/
          {{- end }}
            - name: {{ include "product.fullname" . }}-application-file
              mountPath: /home/application/config/application.properties
              subPath: application.properties
            - name: {{ include "product.fullname" . }}-logback-file
              mountPath: /home/application/config/logback.xml
              subPath: logback.xml
            - name: certs
              mountPath: /home/application/config/certs

#Init container will be copying the product specification directory from provided docker image to our order service pod
      {{- if .Values.productSpecifications.prod }}
      initContainers:
      - name: take-data-of-product-specification
        image: "{{ .Values.global.image.registry }}/{{ .Values.image.init }}:{{ .Values.image.inittag }}"
        command: ['/bin/sh', '-c', 'cp -R /productSpecifications/ /home/application/']
        volumeMounts:
        - name: productspec
          mountPath: /home/application/productSpecifications/
        imagePullPolicy: {{ .Values.global.image.initpullPolicy }}
      {{- end }}
  
      volumes:
        - name: tmp
          emptyDir: {} 
        {{- if .Values.productSpecifications.local }}
        - name: productspecifications
          hostPath:
            path: {{ .Values.productSpecifications.localpath }}
        {{- else if .Values.productSpecifications.prod }}
        - name: productspec
          emptyDir: {}    
        {{- end }}
        {{- if .Values.git.local }}
        - name: git
          hostPath:
            path: {{ .Values.git.localpath }}
        {{- end }}

        - name: {{ include "product.fullname" . }}-logback-file
          configMap:
            name: {{ include "product.fullname" . }}-logback-config

        - name: {{ include "product.fullname" . }}-application-file
          configMap:
            name: {{ include "product.fullname" . }}-application-config

        - name: certs
          secret:
            secretName: {{ .Values.secrets.sslname }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      restartPolicy: Always
