apiVersion: v1
kind: ConfigMap
data:
  logback.xml: |

    <configuration scan="true" scanPeriod="60 seconds">

        <statusListener class="ch.qos.logback.core.status.NopStatusListener"/>
        <contextName>{{ include "product.namingPrefix" . }}product-order</contextName>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{yyyy-MM-dd} %date{HH:mm:ss.SSS} %X{x-correlation-id} %X{x-request-id} %-5level %contextName --- [%thread] %logger{36} %msg%n</pattern>
            </encoder>
        </appender>

        <appender name="ASYNC_STDOUT" class="ch.qos.logback.classic.AsyncAppender">
            <!--queueSize>500</queueSize>
            <discardingThreshold>0</discardingThreshold-->
            <appender-ref ref="STDOUT" />
        </appender>

        <root level="ERROR">
            <appender-ref ref="ASYNC_STDOUT"/>
        </root>

        <root level="INFO">
            <appender-ref ref="ASYNC_STDOUT"/>
        </root>

        <!-- product packages -->
        <logger name="com.org.product" level="info" />

        {{- include "logback.logger" . | nindent 8 }}

    </configuration>

metadata:
  name: {{ include "product.fullname" . }}-logback-config
  namespace: {{ .Release.Namespace }}